ide_uvars := [T__x__O(t), delta__dot(t)];
ide_vars := [s(t), s__n(t), chi(t), V(t), beta(t), psi__dot(t), F__z__fl(t), 
F__z__fr(t), F__z__rl(t), F__z__rr(t), delta(t), T__x(t), omega__fl(t), 
omega__fr(t), omega__rl(t), omega__rr(t)];
ide_eqns_rlx := [diff(s(t),t) = -V(t)*(cos(beta(t))*cos(chi(t))-sin(beta(t))*
sin(chi(t)))/(-1+kappa(s(t))*s__n(t)), diff(s__n(t),t) = V(t)*(cos(beta(t))*
sin(chi(t))+sin(beta(t))*cos(chi(t))), diff(chi(t),t) = -diff(s(t),t)*kappa(s(
t))+psi__dot(t), diff(V(t),t)*m-MFY__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin
(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(
delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(delta(t))+cos(delta(t
))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(
beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta
(t)))*(r*omega__fr(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t
))-1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)
*sin(-delta(t)+beta(t))-MFY__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t)
)*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(
1/2*sin(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(
t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*
sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*
omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*
cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))),F__z__fl(t),phi__fl)*sin(-
delta(t)+beta(t))-MFX__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t)
)*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(1/2*(-
psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(psi__dot(t)*
L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(
delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(
t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)
*w+2*cos(beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)*cos(-delta(t)+beta
(t))-MFX__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t
))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t)
)*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*
cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t))),F__z__fl(t),phi__fl)*cos(-delta(t)+beta(t)
)-cos(beta(t))*MFX__r(arctan(1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-
psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(
r*omega__rr(t)-1/2*psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rr(t),phi__rr)-cos(
beta(t))*MFX__r(arctan(1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*
L__r+sin(beta(t))*V(t))),1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rl
(t)+1/2*psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rl(t),phi__rl)-sin(beta(t))*
MFY__r(arctan(1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(
beta(t))*V(t))),1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rr(t)-1/2*
psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rr(t),phi__rr)-sin(beta(t))*MFY__r(
arctan(1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t)
)*V(t))),1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rl(t)+1/2*psi__dot
(t)*w-cos(beta(t))*V(t)),F__z__rl(t),phi__rl), MFX__f(arctan(1/(1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(
delta(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*psi__dot(t)*L__f+2*sin(
beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta
(t))),F__z__fr(t),phi__fr)*sin(-delta(t)+beta(t))+MFX__f(arctan(1/(1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(psi__dot(t)*w-2*cos(
beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*
sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t
))*V(t))),F__z__fl(t),phi__fl)*sin(-delta(t)+beta(t))-MFY__f(arctan(1/(1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(
delta(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*psi__dot(t)*L__f+2*sin(
beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta
(t))),F__z__fr(t),phi__fr)*cos(-delta(t)+beta(t))-MFY__f(arctan(1/(1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(psi__dot(t)*w-2*cos(
beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*
sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t
))*V(t))),F__z__fl(t),phi__fl)*cos(-delta(t)+beta(t))-cos(beta(t))*MFY__r(
arctan(1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))
*V(t))),1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rr(t)-1/2*psi__dot(t
)*w-cos(beta(t))*V(t)),F__z__rr(t),phi__rr)-cos(beta(t))*MFY__r(arctan(1/(-1/2
*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(-1
/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rl(t)+1/2*psi__dot(t)*w-cos(beta
(t))*V(t)),F__z__rl(t),phi__rl)+sin(beta(t))*MFX__r(arctan(1/(1/2*psi__dot(t)*
w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(1/2*psi__dot(t)
*w+cos(beta(t))*V(t))*(r*omega__rr(t)-1/2*psi__dot(t)*w-cos(beta(t))*V(t)),
F__z__rr(t),phi__rr)+sin(beta(t))*MFX__r(arctan(1/(-1/2*psi__dot(t)*w+cos(beta
(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(-1/2*psi__dot(t)*w+cos(
beta(t))*V(t))*(r*omega__rl(t)+1/2*psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rl(t
),phi__rl)+psi__dot(t)*V(t)*m+V(t)*diff(beta(t),t)*m, I__z*diff(psi__dot(t),t)
+(-MFX__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))
+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2
*cos(beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))
*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)*sin(delta(t))-MFX__f(arctan
(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t
))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(psi__dot(t)*w-2*
cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2
*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*
sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t
))*V(t))),F__z__fl(t),phi__fl)*sin(delta(t))-MFY__f(arctan(1/(1/2*(2*psi__dot(
t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V
(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(delta(t))+
cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*
L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t)
)*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*
sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t))),F__z__fr(
t),phi__fr)*cos(delta(t))-MFY__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(
t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))
*(1/2*sin(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))+cos(delta(t))*(
psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t)
)*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(
r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*
cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))),F__z__fl(t),phi__fl)*cos(
delta(t)))*L__f+L__r*(MFY__r(arctan(1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(
-psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))
*(r*omega__rl(t)+1/2*psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rl(t),phi__rl)+
MFY__r(arctan(1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(
beta(t))*V(t))),1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rr(t)-1/2*
psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rr(t),phi__rr))+(-1/2*MFX__f(arctan(1/(
1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+
2*cos(beta(t))*V(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(beta(t))*V(t))*
sin(delta(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*psi__dot(t)*L__f+2*sin(
beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta
(t))),F__z__fr(t),phi__fr)*cos(delta(t))+1/2*MFX__f(arctan(1/(1/2*(2*psi__dot(
t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*
cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))+cos
(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2
*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(
t))*V(t)))*(r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(
delta(t))+1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))),F__z__fl(t),
phi__fl)*cos(delta(t))+1/2*MFY__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta
(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t))
)*(1/2*(-psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(
psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t)
)*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(
r*omega__fr(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*
(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)*sin(
delta(t))-1/2*MFY__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*
sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(
delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+
sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta
(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/
2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t))),F__z__fl(t),phi__fl)*sin(delta(t))+1/2*
MFX__r(arctan(1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(
beta(t))*V(t))),1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rl(t)+1/2*
psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rl(t),phi__rl)-1/2*MFX__r(arctan(1/(1/2
*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(1/
2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rr(t)-1/2*psi__dot(t)*w-cos(beta(
t))*V(t)),F__z__rr(t),phi__rr))*w, diff(F__z__fl(t),t)*tau__Fz+F__z__fl(t)-1/2
*m*g*L__r/(L__r+L__f)-1/2*h*(MFY__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(
beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta
(t)))*(1/2*(-psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(
psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t)
)*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(
r*omega__fr(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*
(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)*sin(
delta(t))+MFY__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(
delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(
delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+
sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta
(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/
2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t))),F__z__fl(t),phi__fl)*sin(delta(t))-MFX__f(
arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(
beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)
))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)*cos(delta(t))-MFX__f(arctan
(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t
))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(psi__dot(t)*w-2*
cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2
*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*
sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t
))*V(t))),F__z__fl(t),phi__fl)*cos(delta(t))-MFX__r(arctan(1/(1/2*psi__dot(t)*
w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(1/2*psi__dot(t)
*w+cos(beta(t))*V(t))*(r*omega__rr(t)-1/2*psi__dot(t)*w-cos(beta(t))*V(t)),
F__z__rr(t),phi__rr)-MFX__r(arctan(1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-
psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*
(r*omega__rl(t)+1/2*psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rl(t),phi__rl))/(
L__r+L__f)+1/(L__r+L__f)*L__r*h*(MFX__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*
sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(
delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(delta(t))+cos(delta(t
))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(
beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta
(t)))*(r*omega__fr(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t
))-1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)
*sin(delta(t))+MFX__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*
sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(
delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+
sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta
(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/
2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t))),F__z__fl(t),phi__fl)*sin(delta(t))+MFY__f(
arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(
beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)
))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)*cos(delta(t))+MFY__f(arctan
(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t
))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(psi__dot(t)*w-2*
cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2
*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*
sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t
))*V(t))),F__z__fl(t),phi__fl)*cos(delta(t))+MFY__r(arctan(1/(1/2*psi__dot(t)*
w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(1/2*psi__dot(t)
*w+cos(beta(t))*V(t))*(r*omega__rr(t)-1/2*psi__dot(t)*w-cos(beta(t))*V(t)),
F__z__rr(t),phi__rr)+MFY__r(arctan(1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-
psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*
(r*omega__rl(t)+1/2*psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rl(t),phi__rl))/w,
diff(F__z__fr(t),t)*tau__Fz+F__z__fr(t)-1/2*m*g*L__r/(L__r+L__f)-1/2*h*(MFY__f
(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(
beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)
))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)*sin(delta(t))+MFY__f(arctan
(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t
))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(psi__dot(t)*w-2*
cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2
*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*
sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t
))*V(t))),F__z__fl(t),phi__fl)*sin(delta(t))-MFX__f(arctan(1/(1/2*(2*psi__dot(
t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V
(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(delta(t))+
cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*
L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t)
)*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*
sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t))),F__z__fr(
t),phi__fr)*cos(delta(t))-MFX__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(
t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))
*(1/2*sin(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))+cos(delta(t))*(
psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t)
)*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(
r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*
cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))),F__z__fl(t),phi__fl)*cos(
delta(t))-MFX__r(arctan(1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*
L__r+sin(beta(t))*V(t))),1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rr(
t)-1/2*psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rr(t),phi__rr)-MFX__r(arctan(1/(
-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t))),1
/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rl(t)+1/2*psi__dot(t)*w-cos(
beta(t))*V(t)),F__z__rl(t),phi__rl))/(L__r+L__f)-1/(L__r+L__f)*L__r*h*(MFX__f(
arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(
beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)
))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)*sin(delta(t))+MFX__f(arctan
(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t
))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(psi__dot(t)*w-2*
cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2
*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*
sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t
))*V(t))),F__z__fl(t),phi__fl)*sin(delta(t))+MFY__f(arctan(1/(1/2*(2*psi__dot(
t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V
(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(delta(t))+
cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*
L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t)
)*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*
sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t))),F__z__fr(
t),phi__fr)*cos(delta(t))+MFY__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(
t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))
*(1/2*sin(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))+cos(delta(t))*(
psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t)
)*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(
r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*
cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))),F__z__fl(t),phi__fl)*cos(
delta(t))+MFY__r(arctan(1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*
L__r+sin(beta(t))*V(t))),1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rr(
t)-1/2*psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rr(t),phi__rr)+MFY__r(arctan(1/(
-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t))),1
/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rl(t)+1/2*psi__dot(t)*w-cos(
beta(t))*V(t)),F__z__rl(t),phi__rl))/w, diff(F__z__rl(t),t)*tau__Fz+F__z__rl(t
)-1/2*L__f*g*m/(L__r+L__f)+1/2*h*(MFY__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*
sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(
delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(delta(t))+cos(delta(t
))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(
beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta
(t)))*(r*omega__fr(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t
))-1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)
*sin(delta(t))+MFY__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*
sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(
delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+
sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta
(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/
2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t))),F__z__fl(t),phi__fl)*sin(delta(t))-MFX__f(
arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(
beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)
))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)*cos(delta(t))-MFX__f(arctan
(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t
))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(psi__dot(t)*w-2*
cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2
*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*
sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t
))*V(t))),F__z__fl(t),phi__fl)*cos(delta(t))-MFX__r(arctan(1/(1/2*psi__dot(t)*
w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(1/2*psi__dot(t)
*w+cos(beta(t))*V(t))*(r*omega__rr(t)-1/2*psi__dot(t)*w-cos(beta(t))*V(t)),
F__z__rr(t),phi__rr)-MFX__r(arctan(1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-
psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*
(r*omega__rl(t)+1/2*psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rl(t),phi__rl))/(
L__r+L__f)+1/(L__r+L__f)*L__f*h*(MFX__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*
sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(
delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(delta(t))+cos(delta(t
))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(
beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta
(t)))*(r*omega__fr(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t
))-1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)
*sin(delta(t))+MFX__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*
sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(
delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+
sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta
(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/
2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t))),F__z__fl(t),phi__fl)*sin(delta(t))+MFY__f(
arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(
beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)
))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)*cos(delta(t))+MFY__f(arctan
(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t
))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(psi__dot(t)*w-2*
cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2
*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*
sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t
))*V(t))),F__z__fl(t),phi__fl)*cos(delta(t))+MFY__r(arctan(1/(1/2*psi__dot(t)*
w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(1/2*psi__dot(t)
*w+cos(beta(t))*V(t))*(r*omega__rr(t)-1/2*psi__dot(t)*w-cos(beta(t))*V(t)),
F__z__rr(t),phi__rr)+MFY__r(arctan(1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-
psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*
(r*omega__rl(t)+1/2*psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rl(t),phi__rl))/w,
diff(F__z__rr(t),t)*tau__Fz+F__z__rr(t)-1/2*L__f*g*m/(L__r+L__f)+1/2*h*(MFY__f
(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(
beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)
))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)*sin(delta(t))+MFY__f(arctan
(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t
))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(psi__dot(t)*w-2*
cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2
*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*
sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t
))*V(t))),F__z__fl(t),phi__fl)*sin(delta(t))-MFX__f(arctan(1/(1/2*(2*psi__dot(
t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V
(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(delta(t))+
cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*
L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t)
)*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*
sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t))),F__z__fr(
t),phi__fr)*cos(delta(t))-MFX__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(
t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))
*(1/2*sin(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))+cos(delta(t))*(
psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t)
)*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(
r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*
cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))),F__z__fl(t),phi__fl)*cos(
delta(t))-MFX__r(arctan(1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*
L__r+sin(beta(t))*V(t))),1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rr(
t)-1/2*psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rr(t),phi__rr)-MFX__r(arctan(1/(
-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t))),1
/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rl(t)+1/2*psi__dot(t)*w-cos(
beta(t))*V(t)),F__z__rl(t),phi__rl))/(L__r+L__f)-1/(L__r+L__f)*L__f*h*(MFX__f(
arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(
beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)
))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)*sin(delta(t))+MFX__f(arctan
(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t
))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(psi__dot(t)*w-2*
cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2
*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*
sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t
))*V(t))),F__z__fl(t),phi__fl)*sin(delta(t))+MFY__f(arctan(1/(1/2*(2*psi__dot(
t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V
(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(delta(t))+
cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*
L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t)
)*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*
sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t))),F__z__fr(
t),phi__fr)*cos(delta(t))+MFY__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(
t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))
*(1/2*sin(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))+cos(delta(t))*(
psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t)
)*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(
r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*
cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))),F__z__fl(t),phi__fl)*cos(
delta(t))+MFY__r(arctan(1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*
L__r+sin(beta(t))*V(t))),1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rr(
t)-1/2*psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rr(t),phi__rr)+MFY__r(arctan(1/(
-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t))),1
/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rl(t)+1/2*psi__dot(t)*w-cos(
beta(t))*V(t)),F__z__rl(t),phi__rl))/w, I__w*diff(omega__rr(t),t)+MFX__r(
arctan(1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))
*V(t))),1/(1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rr(t)-1/2*psi__dot(t
)*w-cos(beta(t))*V(t)),F__z__rr(t),phi__rr)*r-1/2*(1-gamma__tr)*posPart(T__x(t
))-1/2*(1-gamma__br)*negPart(T__x(t)), I__w*diff(omega__rl(t),t)+MFX__r(arctan
(1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t)
)),1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rl(t)+1/2*psi__dot(t)*w-
cos(beta(t))*V(t)),F__z__rl(t),phi__rl)*r-1/2*(1-gamma__tr)*posPart(T__x(t))-1
/2*(1-gamma__br)*negPart(T__x(t)), I__w*diff(omega__fr(t),t)+r*MFX__f(arctan(1
/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*
w+2*cos(beta(t))*V(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(beta(t))*V(t)
)*sin(delta(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2
*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*psi__dot(t)*L__f+2*sin(
beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta
(t))),F__z__fr(t),phi__fr)-1/2*gamma__tr*posPart(T__x(t))-1/2*gamma__br*
negPart(T__x(t)), I__w*diff(omega__fl(t),t)+r*MFX__f(arctan(1/(1/2*(2*psi__dot
(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2
*cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))+
cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*
L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos
(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*
sin(delta(t))+1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))),F__z__fl(
t),phi__fl)-1/2*gamma__tr*posPart(T__x(t))-1/2*gamma__br*negPart(T__x(t)), 
diff(delta(t),t)-delta__dot(t)*delta__scale, diff(T__x(t),t)*tau__T__x+T__x(t)
-T__x__O(t)];
sol_acc := [a__x(t) = (-MFY__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t)
)*V(t))*sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(
1/2*(-psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(psi__dot
(t)*L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*
sin(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(r*
omega__fr(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)*sin(
delta(t))-MFY__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(
delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(
delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+
sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta
(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/
2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t))),F__z__fl(t),phi__fl)*sin(delta(t))+MFX__f(
arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(
beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)
))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)*cos(delta(t))+MFX__f(arctan
(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t
))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(psi__dot(t)*w-2*
cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2
*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*
sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t
))*V(t))),F__z__fl(t),phi__fl)*cos(delta(t))+MFX__r(arctan(1/(1/2*psi__dot(t)*
w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(1/2*psi__dot(t)
*w+cos(beta(t))*V(t))*(r*omega__rr(t)-1/2*psi__dot(t)*w-cos(beta(t))*V(t)),
F__z__rr(t),phi__rr)+MFX__r(arctan(1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-
psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*
(r*omega__rl(t)+1/2*psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rl(t),phi__rl))/m,
a__y(t) = (MFX__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(
delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(1/2*(-
psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(psi__dot(t)*
L__f+sin(beta(t))*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(
delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(
t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)
*w+2*cos(beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)*sin(delta(t))+
MFX__f(arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/
2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t)
)*V(t)))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*
cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t))),F__z__fl(t),phi__fl)*sin(delta(t))+MFY__f(
arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(1/2*(-psi__dot(t)*w-2*cos(
beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)
))),1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))+1/2*(
psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(r*omega__fr(t)-1/2*(2*
psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t)*w+2*cos(
beta(t))*V(t))*cos(delta(t))),F__z__fr(t),phi__fr)*cos(delta(t))+MFY__f(arctan
(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t
))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))*(1/2*sin(delta(t))*(psi__dot(t)*w-2*
cos(beta(t))*V(t))+cos(delta(t))*(psi__dot(t)*L__f+sin(beta(t))*V(t)))),1/(1/2
*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(
psi__dot(t)*w-2*cos(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*
sin(beta(t))*V(t))*sin(delta(t))+1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t
))*V(t))),F__z__fl(t),phi__fl)*cos(delta(t))+MFY__r(arctan(1/(1/2*psi__dot(t)*
w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(1/2*psi__dot(t)
*w+cos(beta(t))*V(t))*(r*omega__rr(t)-1/2*psi__dot(t)*w-cos(beta(t))*V(t)),
F__z__rr(t),phi__rr)+MFY__r(arctan(1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-
psi__dot(t)*L__r+sin(beta(t))*V(t))),1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*
(r*omega__rl(t)+1/2*psi__dot(t)*w-cos(beta(t))*V(t)),F__z__rl(t),phi__rl))/m]
;
practical__side__slips := [alpha__rr(t) = -arctan(1/(1/2*psi__dot(t)*w+cos(
beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t))), alpha__rl(t) = -arctan(
1/(-1/2*psi__dot(t)*w+cos(beta(t))*V(t))*(-psi__dot(t)*L__r+sin(beta(t))*V(t))
), alpha__fr(t) = -arctan(1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(
delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(1/2*(-
psi__dot(t)*w-2*cos(beta(t))*V(t))*sin(delta(t))+cos(delta(t))*(psi__dot(t)*
L__f+sin(beta(t))*V(t)))), alpha__fl(t) = -arctan(1/(1/2*(2*psi__dot(t)*L__f+2
*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(
t))*V(t)))*(1/2*sin(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t))+cos(delta(t)
)*(psi__dot(t)*L__f+sin(beta(t))*V(t))))];
practical__long__slips := [kappa__rr(t) = 1/(1/2*psi__dot(t)*w+cos(beta(t))*V(
t))*(r*omega__rr(t)-1/2*psi__dot(t)*w-cos(beta(t))*V(t)), kappa__rl(t) = 1/(-1
/2*psi__dot(t)*w+cos(beta(t))*V(t))*(r*omega__rl(t)+1/2*psi__dot(t)*w-cos(beta
(t))*V(t)), kappa__fr(t) = 1/(1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin
(delta(t))+1/2*(psi__dot(t)*w+2*cos(beta(t))*V(t))*cos(delta(t)))*(r*omega__fr
(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*(psi__dot(t
)*w+2*cos(beta(t))*V(t))*cos(delta(t))), kappa__fl(t) = 1/(1/2*(2*psi__dot(t)*
L__f+2*sin(beta(t))*V(t))*sin(delta(t))-1/2*cos(delta(t))*(psi__dot(t)*w-2*cos
(beta(t))*V(t)))*(r*omega__fl(t)-1/2*(2*psi__dot(t)*L__f+2*sin(beta(t))*V(t))*
sin(delta(t))+1/2*cos(delta(t))*(psi__dot(t)*w-2*cos(beta(t))*V(t)))];
subs_fz := [F__z__fl(t) = F__z__f0-Delta__Fzx(t)-1/(L__r+L__f)*L__r*Delta__Fzy
(t), F__z__fr(t) = F__z__f0-Delta__Fzx(t)+1/(L__r+L__f)*L__r*Delta__Fzy(t), 
F__z__rl(t) = F__z__r0+Delta__Fzx(t)-1/(L__r+L__f)*L__f*Delta__Fzy(t), 
F__z__rr(t) = F__z__r0+Delta__Fzx(t)+1/(L__r+L__f)*L__f*Delta__Fzy(t)];
vertical_loads_SS := [F__z__fl(t) = 1/2*m*g*L__r/(L__r+L__f)+1/2*h*(F__y__fr(t
)*sin(delta(t))+F__y__fl(t)*sin(delta(t))-F__x__fr(t)*cos(delta(t))-F__x__fl(t
)*cos(delta(t))-F__x__rr(t)-F__x__rl(t))/(L__r+L__f)-1/(L__r+L__f)*L__r*h*(
F__x__fr(t)*sin(delta(t))+F__x__fl(t)*sin(delta(t))+F__y__fr(t)*cos(delta(t))+
F__y__fl(t)*cos(delta(t))+F__y__rr(t)+F__y__rl(t))/w, F__z__fr(t) = 1/2*m*g*
L__r/(L__r+L__f)+1/2*h*(F__y__fr(t)*sin(delta(t))+F__y__fl(t)*sin(delta(t))-
F__x__fr(t)*cos(delta(t))-F__x__fl(t)*cos(delta(t))-F__x__rr(t)-F__x__rl(t))/(
L__r+L__f)+1/(L__r+L__f)*L__r*h*(F__x__fr(t)*sin(delta(t))+F__x__fl(t)*sin(
delta(t))+F__y__fr(t)*cos(delta(t))+F__y__fl(t)*cos(delta(t))+F__y__rr(t)+
F__y__rl(t))/w, F__z__rl(t) = 1/2*L__f*g*m/(L__r+L__f)-1/2*h*(F__y__fr(t)*sin(
delta(t))+F__y__fl(t)*sin(delta(t))-F__x__fr(t)*cos(delta(t))-F__x__fl(t)*cos(
delta(t))-F__x__rr(t)-F__x__rl(t))/(L__r+L__f)-1/(L__r+L__f)*L__f*h*(F__x__fr(
t)*sin(delta(t))+F__x__fl(t)*sin(delta(t))+F__y__fr(t)*cos(delta(t))+F__y__fl(
t)*cos(delta(t))+F__y__rr(t)+F__y__rl(t))/w, F__z__rr(t) = 1/2*L__f*g*m/(L__r+
L__f)-1/2*h*(F__y__fr(t)*sin(delta(t))+F__y__fl(t)*sin(delta(t))-F__x__fr(t)*
cos(delta(t))-F__x__fl(t)*cos(delta(t))-F__x__rr(t)-F__x__rl(t))/(L__r+L__f)+1
/(L__r+L__f)*L__f*h*(F__x__fr(t)*sin(delta(t))+F__x__fl(t)*sin(delta(t))+
F__y__fr(t)*cos(delta(t))+F__y__fl(t)*cos(delta(t))+F__y__rr(t)+F__y__rl(t))/w
];
static_loads_sol := [F__z__f0 = 1/2*m*g*L__r/(L__r+L__f), F__z__r0 = 1/2*L__f*
g*m/(L__r+L__f)];
load_transfers_sol := [Delta__Fzx(t) = -1/2*h*(F__y__fr(t)*sin(delta(t))+
F__y__fl(t)*sin(delta(t))-F__x__fr(t)*cos(delta(t))-F__x__fl(t)*cos(delta(t))-
F__x__rr(t)-F__x__rl(t))/(L__r+L__f), Delta__Fzy(t) = h*(F__x__fr(t)*sin(delta
(t))+F__x__fl(t)*sin(delta(t))+F__y__fr(t)*cos(delta(t))+F__y__fl(t)*cos(delta
(t))+F__y__rr(t)+F__y__rl(t))/w];
maps_tyre_force_fy := [F__y__fl(t) = MFY__f(-alpha__fl(t),kappa__fl(t),
F__z__fl(t),phi__fl), F__y__fr(t) = MFY__f(-alpha__fr(t),kappa__fr(t),F__z__fr
(t),phi__fr), F__y__rl(t) = MFY__r(-alpha__rl(t),kappa__rl(t),F__z__rl(t),
phi__rl), F__y__rr(t) = MFY__r(-alpha__rr(t),kappa__rr(t),F__z__rr(t),phi__rr)
];
maps_tyre_force_fx := [F__x__fl(t) = MFX__f(-alpha__fl(t),kappa__fl(t),
F__z__fl(t),phi__fl), F__x__fr(t) = MFX__f(-alpha__fr(t),kappa__fr(t),F__z__fr
(t),phi__fr), F__x__rl(t) = MFX__r(-alpha__rl(t),kappa__rl(t),F__z__rl(t),
phi__rl), F__x__rr(t) = MFX__r(-alpha__rr(t),kappa__rr(t),F__z__rr(t),phi__rr)
];
maps_tyre_moment_sa := [AM__fl(t) = MFSA__f(-alpha__fl(t),kappa__fl(t),
F__z__fl(t),phi__fl), AM__fr(t) = MFSA__f(-alpha__fr(t),kappa__fr(t),F__z__fr(
t),phi__fr), AM__rl(t) = MFSA__r(-alpha__rl(t),kappa__rl(t),F__z__rl(t),
phi__rl), AM__rr(t) = MFSA__r(-alpha__rr(t),kappa__rr(t),F__z__rr(t),phi__rr)]
;
powertrain__eqns := [T__fl(t) = 1/2*gamma__tr*posPart(T__x(t))+1/2*gamma__br*
negPart(T__x(t)), T__fr(t) = 1/2*gamma__tr*posPart(T__x(t))+1/2*gamma__br*
negPart(T__x(t)), T__rl(t) = 1/2*(1-gamma__tr)*posPart(T__x(t))+1/2*(1-
gamma__br)*negPart(T__x(t)), T__rr(t) = 1/2*(1-gamma__tr)*posPart(T__x(t))+1/2
*(1-gamma__br)*negPart(T__x(t))];
